data:
    dataset: "LOL_Origin"
    image_size: 64
    channels: 3
    num_workers: 32
    data_dir: "/home/eileen/Diffusion/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    width: 64
    enc_blk_nums: [1, 2, 2, 24, 1]
    middle_blk_num: 4
    dec_blk_nums: [1, 1, 1, 1, 1]

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 4 
    batch_size: 4
    n_epochs: 5000  
    n_iters: 800000 
    snapshot_freq: 5000 
    validation_freq: 5000 

sampling:
    batch_size:  16 #4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002 
    amsgrad: False
    eps: 0.0000001
